routes:
  - path: "/api/hello"
    backend: "http://backend-a-service:8081"
    backendPath: "/hello"
    requiresAuth: true
    allowedRoles: 
      - user
      - premium
    maxTokens: 100 
    refillRate: 10
  - path: "/api/register"
    backend: "http://backend-b-service:8082"
    backendPath: "/register"
    requiresAuth: true
    allowedRoles: 
      - user
      - premium
    maxTokens: 100
    refillRate: 10

